// Wave 3 — six domain-F (Behavior Assessment) depth days, 123-128.
// Validate with: node tools/qa/add-days.mjs .bcba-build/wave3/wave3-days.mjs
[
  {
    day: 123,
    domain: "Behavior Assessment",
    taskCode: "F.1 · Records Review",
    taskDesc: "Identify relevant sources of information in records (e.g., educational, medical, historical) at the outset of the case.",
    concept: {
      title: "Records Review: Setting Events and Treatment History",
      body: "The sixth-edition outline puts records at the outset for a reason: what the chart contains changes how the assessment should be designed, not merely what the report says about background. Three record classes carry distinct information — educational, medical, and historical — and each answers a different question about the case.\n\nMedical and historical records identify setting events, and the diagnostic signature is behavior that appears in episodes rather than continuously. Recurrent ear infection, constipation, seizure activity, allergy symptoms, menstrual discomfort, disrupted sleep and medication changes all alter the value of reinforcers. When such a variable cycles, an analysis run during a symptom-free phase can produce a clean negative that is simply wrong for the phase in which the behavior actually occurs.\n\nEducational and treatment records answer a different question: what has already been tried, and what happened. Prior functional assessments and their conclusions, prior behavior plans and the data on their implementation, restrictive procedures previously used, placement changes and incident reports all narrow the hypothesis space and prevent repeating a procedure that has already failed. They also document a learning history that shapes what current responding means.\n\nThe distinction worth holding is between records read as background and records read as variables. Deciding whether services are warranted, and referring a plausible medical cause for evaluation before any analysis, is a separate obligation that still runs first. What records contribute to assessment design is narrower and more testable: when to schedule the analysis, which conditions to include, and which findings to distrust. A discrepancy between what the record documents and what an informant reports is itself assessment data."
    },
    research: {
      citation: "O'Reilly, M. F. (1997). Functional analysis of episodic self-injury correlated with recurrent otitis media. Journal of Applied Behavior Analysis, 30(1), 165–167.",
      summary: "O'Reilly reported a single case that makes the argument for records review concrete. A child with moderate developmental disabilities engaged in self-injury that occurred episodically rather than continuously, and the record documented recurrent otitis media. The functional analysis examined both the consequences that maintained the self-injury and the relationship between those consequences and the ear infections. The result was categorical: self-injury occurred only during periods of otitis media. O'Reilly proposed, in hedged wording worth preserving, that otitis media may have served as an establishing operation related to escape from ambient noise. This is a brief single-case report, so it demonstrates rather than establishes; its value is showing that a variable sitting in the chart determined whether the analysis would find anything at all."
    },
    application: "Before you schedule an analysis, pull the record and read it for cycles rather than for background. Note recurrent conditions, medication changes, sleep and bowel patterns, and the dates of previous behavior plans. If the referral describes behavior in episodes, ask the caregiver what distinguishes a bad week from a good one, then arrange your sessions so they sample both. Record what has already been tried and what the data showed.",
    questions: [
      { q: "Records show a learner's self-injury coincides with recurrent ear infections. The functional analysis should therefore:", options: ["A. Sample both symptomatic and symptom-free periods", "B. Be postponed until the infections resolve permanently", "C. Replace the alone condition with a pain probe", "D. Treat the infections as an unmeasurable confound"], answer: "A", rationale: "A condition that cycles can only be detected while it is in effect. Running the analysis exclusively during a symptom-free phase risks a false negative for the phase in which behavior actually occurs." },
      { q: "The most useful content in a prior behavior intervention plan is:", options: ["A. The diagnosis and eligibility category recorded at intake", "B. The credentials of the analyst who authored the plan", "C. The procedures used and what the data showed happened", "D. The number of goals and objectives it listed"], answer: "C", rationale: "What was implemented and what followed narrows the hypothesis space and prevents repeating a failed procedure. Credentials, diagnosis and goal counts describe the document rather than the client's response to it." },
      { q: "Reading records as variables rather than as background primarily means using them to:", options: ["A. Shape when the assessment runs and what it includes", "B. Establish the client's eligibility for funded services", "C. Satisfy the documentation requirements of the funder", "D. Summarize the referral concern for the written report"], answer: "A", rationale: "Records used as variables change assessment design — the timing of the analysis and the conditions included. Eligibility, funder documentation and referral summaries are administrative uses that leave the assessment itself unchanged." }
    ]
  },
  {
    day: 124,
    domain: "Behavior Assessment",
    taskCode: "F.5 · Conditional Probability",
    taskDesc: "Design and evaluate descriptive assessments.",
    concept: {
      title: "Conditional Probability and Contingency in Descriptive Data",
      body: "Descriptive assessment is routinely summarized with a claim like \"attention followed the behavior eighty percent of the time.\" That number alone establishes nothing. A contingency is a differential relation, and a frequency count of what followed behavior cannot express one.\n\nTwo quantities are needed. The unconditional, or background, probability is how likely the consequence is across the observation generally, irrespective of the target behavior. The conditional probability is how likely it is in the moments immediately following the behavior. A contingency is indicated only when the conditional probability exceeds the unconditional one; Vollmer and colleagues termed that comparison a contingency value.\n\nThe arithmetic changes conclusions in both directions. Attention following eighty percent of episodes looks damning until you find the caregiver delivers attention eighty percent of the time regardless — the consequence is frequent but not differential, so no contingency is demonstrated. Conversely, a consequence following only fifteen percent of episodes can indicate a strong contingency when its background probability is near zero, which is why low-frequency consequences are so easily dismissed by eye.\n\nContext matters as much as arithmetic. Contingency values should be computed within the establishing operations that make the reinforcer relevant — diverted attention, instructional demands, restricted access — because a contingency operating only while an establishing operation is in effect gets diluted toward zero when averaged across a whole session. Two cautions close the method. Naturally occurring contingencies are genuinely difficult to detect, and this analysis identifies possible contingencies only. It sharpens a descriptive account; it does not convert one into an experimental demonstration."
    },
    research: {
      citation: "Vollmer, T. R., Borrero, J. C., Wright, C. S., Van Camp, C., & Lalli, J. S. (2001). Identifying possible contingencies during descriptive analyses of severe behavior disorders. Journal of Applied Behavior Analysis, 34(3), 269–287.",
      summary: "Vollmer and colleagues observed eleven individuals with developmental disabilities and severe behavior problems interacting with their primary care providers in simulated environments. For each, they compared the probability of obtaining attention, escape from instructional demands, or access to materials following instances of problem behavior against the background probability of those same events. Their contribution was to evaluate these comparative probabilities, which they termed contingency values, specifically in the context of relevant establishing operations such as diverted attention, instructional demands and restricted access. They reported the method useful for identifying relations between behavior and subsequent environmental events, and discussed both the implications for linking descriptive and functional analyses and the genuine difficulty of identifying naturally occurring contingencies."
    },
    application: "Stop reporting raw consequence counts in your descriptive summaries. For each candidate consequence, compute how often it followed the behavior and how often it occurred otherwise, and report the pair. Do the computation separately within the conditions that make each reinforcer relevant rather than across the whole observation. Then state plainly in the report that a positive contingency value identifies a hypothesis to test experimentally, not a demonstrated function.",
    questions: [
      { q: "Attention follows 80% of problem behavior episodes, and is also delivered during 80% of intervals generally. This indicates:", options: ["A. A strong attention contingency", "B. No differential attention contingency", "C. An escape contingency operating instead of attention", "D. An unreliable observation record"], answer: "B", rationale: "A contingency requires the consequence to be more probable after the behavior than otherwise. Equal conditional and unconditional probabilities mean attention is frequent but not differentially related to responding." },
      { q: "A consequence follows only 15% of episodes but occurs in under 1% of other intervals. This most likely reflects:", options: ["A. Too little data to interpret", "B. A weak and clinically irrelevant relation", "C. Observer drift across sessions", "D. A meaningful contingency worth testing"], answer: "D", rationale: "Contingency strength is the gap between conditional and background probability, not the raw conditional value. A low-frequency consequence against a near-zero baseline represents a substantial differential relation." },
      { q: "Computing contingency values within relevant establishing operations rather than across the whole session prevents:", options: ["A. Observers disagreeing about the behavior definitions used", "B. The background probability from ever reaching zero", "C. Dilution of a contingency that operates only situationally", "D. The need for any experimental analysis afterward"], answer: "C", rationale: "A contingency active only while an establishing operation is in effect is averaged toward zero across a full session. Restricting the computation to relevant contexts preserves the relation the analysis is meant to detect." }
    ]
  },
  {
    day: 125,
    domain: "Behavior Assessment",
    taskCode: "F.6 · Practical Variants",
    taskDesc: "Design and evaluate functional analyses.",
    concept: {
      title: "Brief and Trial-Based Functional Analysis Formats",
      body: "The standard functional analysis assumes resources many settings do not have: a controlled room, repeated sessions per condition, and staff trained to run them. Several variants preserve the core logic of Iwata and colleagues' methodology while changing how sessions are scheduled and where they occur.\n\nThe brief functional analysis compresses the assessment into a single outpatient appointment. Northup and colleagues (1991) ran one session per condition inside a ninety-minute evaluation, then added a contingency reversal in which the reinforcer identified for problem behavior was delivered instead for an alternative mand. The reversal is the important part: it tests the identified contingency rather than resting on a single unreplicated comparison. Without replication, a negative result carries little weight.\n\nThe trial-based functional analysis moves the assessment into the natural setting. Bloom and colleagues (2011) interspersed brief trials among ordinary classroom activities. Each trial ran control, test, and control segments of two minutes each, a segment ended as soon as problem behavior occurred, and observers scored only whether behavior was present in the segment.\n\nTwo findings temper the appeal. Correspondence with the standard analysis was complete in six of ten cases and partial in a seventh, with failures traced to brief trials providing limited exposure to establishing operations and to classroom contingencies suppressing responding. And the trial-based analysis was not actually faster — it consumed slightly more total assessment time than the standard analysis. These formats buy feasibility, not speed, and an unclear or noncorresponding result calls for a standard analysis rather than acceptance."
    },
    research: {
      citation: "Bloom, S. E., Iwata, B. A., Fritz, J. N., Roscoe, E. M., & Carreau, A. B. (2011). Classroom application of a trial-based functional analysis. Journal of Applied Behavior Analysis, 44(1), 19–31.",
      summary: "Bloom and colleagues evaluated a trial-based approach with ten students referred for problem behavior, interspersing assessment trials among classroom activities throughout the day and comparing outcomes against traditional functional analyses. Results corresponded in six of the ten cases and partially corresponded in a seventh. The standard analysis suggested reasons for noncorrespondence in two cases, and those explanations were verified when portions of the trial-based analysis were modified and repeated: one student's function emerged only when test segments were lengthened, and another's aggression had been suppressed by the classroom teacher's presence. The authors positioned trial-based analysis as a viable method when resources for a standard analysis are unavailable, and suggested longer test segments than control segments might improve accuracy."
    },
    application: "If you are asked to assess a student the school will not release from class, propose a trial-based analysis rather than declining. Budget for it honestly — it is more feasible than a standard analysis, not quicker. Script the control and test segments before entering the room, decide in advance who will be present, and treat teacher presence as a variable. When results are unclear or conflict with report, escalate to a standard analysis.",
    questions: [
      { q: "A trial-based functional analysis and a standard analysis produce conflicting functions for the same student. The analyst should:", options: ["A. Average the two outcomes into a combined hypothesis", "B. Adopt the trial-based result for its ecological validity", "C. Examine the discrepancy and trust the standard analysis", "D. Repeat the trial-based analysis until results agree"], answer: "C", rationale: "Trial-based formats trade experimental control for feasibility, so noncorrespondence signals a limitation of the screening format. Bloom and colleagues resolved such conflicts by modifying trials and verifying against the standard analysis." },
      { q: "The contingency reversal phase of a brief functional analysis serves primarily to:", options: ["A. Verify the identified contingency using an alternative response", "B. Reduce the risk of injury during assessment sessions", "C. Shorten the appointment by removing a control condition", "D. Establish the client's preference among available reinforcers"], answer: "A", rationale: "A brief analysis runs one session per condition, so it lacks replication. Delivering the identified reinforcer for an alternative mand tests whether that contingency genuinely controls responding rather than relying on a single comparison." },
      { q: "Bloom et al. (2011) found that trial-based functional analysis, relative to standard functional analysis, required:", options: ["A. Substantially less total assessment time", "B. Slightly more total assessment time", "C. Identical time but fewer trained observers", "D. Less time only for escape-maintained behavior"], answer: "B", rationale: "The trial-based analysis consumed marginally more total assessment time than the standard analysis. Its advantage is that the time is distributed into the classroom day rather than requiring a separate controlled setting." }
    ]
  },
  {
    day: 126,
    domain: "Behavior Assessment",
    taskCode: "F.6 · Synthesized and Precursor Analyses",
    taskDesc: "Design and evaluate functional analyses.",
    concept: {
      title: "Synthesized and Precursor Functional Analysis Approaches",
      body: "Two problems push analysts away from the standard format. One is danger: the standard analysis requires evoking and documenting the target behavior repeatedly, which for severe self-injury or aggression can be unacceptable. The other is efficiency, meaning the speed with which an analysis produces a convincing demonstration of control.\n\nPrecursor analysis addresses danger. Smith and Churchill (2002) arranged experimental analysis contingencies for behaviors that had been observed to reliably precede the target response — the whining or posturing that dependably comes before an attack — rather than for the target itself. For each of their four participants, the maintaining variables for the problem behavior could be inferred from the precursor analysis. The method depends entirely on the precursor genuinely and reliably preceding the target; that relation must be documented, not assumed.\n\nThe interview-informed synthesized contingency analysis addresses efficiency, and it differs from brief and trial-based formats in kind rather than degree. Those variants preserve the core components of the standard methodology and change the schedule or setting. This one modifies the core components: an open-ended interview identifies the specific contingency caregivers describe, the putative reinforcers are combined into a single synthesized test condition, and that condition is compared against one matched control.\n\nThe trade is explicit. Synthesizing reinforcers identifies a contingency sufficient to evoke the behavior but does not isolate which component is necessary, which the standard analysis does. Both approaches also inherit informant error, since each begins from what someone reports rather than from direct manipulation alone."
    },
    research: {
      citation: "Jessel, J., Hanley, G. P., & Ghaemmaghami, M. (2016). Interview-informed synthesized contingency analyses: Thirty replications and reanalysis. Journal of Applied Behavior Analysis, 49(3), 576–595.",
      summary: "Jessel, Hanley and Ghaemmaghami framed their question around analytic efficiency — the speed with which a functional analysis provides a convincing demonstration of the variables influencing problem behavior. They noted that multiple alternative formats improve efficiency while maintaining the core components of the Iwata et al. procedures, whereas the approach they examined improves it by modifying those components. Study 1 described thirty applications of the interview-informed synthesized contingency analysis introduced by Hanley, Jin, Vanselow and Hanratty (2014), which required an average of twenty-five minutes of analysis. Study 2 reanalyzed only the first sessions of those analyses and found that controlling contingencies could be identified within three to five minutes in eighty percent of cases."
    },
    application: "When a referral describes behavior too dangerous to evoke repeatedly, do not simply skip the analysis. Ask staff what reliably happens in the thirty seconds before an episode, then verify that sequence with direct observation before you build an analysis around it. If you use a synthesized condition, write in the report which reinforcers were combined and state that the analysis identified a sufficient contingency rather than isolating a necessary one.",
    questions: [
      { q: "Before running a functional analysis on a precursor rather than the target behavior, the analyst must first establish that the precursor:", options: ["A. Occurs at a higher rate than the target behavior", "B. Belongs to a different response class than the target", "C. Is topographically similar to the target behavior", "D. Precedes the target behavior reliably"], answer: "D", rationale: "The inference from precursor to target rests entirely on the precursor dependably preceding it. Smith and Churchill selected precursors observed to reliably precede the target, and without that documented relation the analysis tests an unrelated response." },
      { q: "A synthesized contingency analysis differs most fundamentally from brief and trial-based formats in that it:", options: ["A. Requires substantially more session time overall", "B. Modifies the core components of the standard methodology", "C. Eliminates the need for any control condition", "D. Applies only to behavior maintained by automatic reinforcement"], answer: "B", rationale: "Brief and trial-based analyses retain the standard components while altering scheduling or setting. The synthesized analysis changes the components themselves by combining reinforcers into one test condition compared against a single matched control." },
      { q: "The principal analytic cost of combining several putative reinforcers into one test condition is that the result:", options: ["A. Cannot be used to design any treatment", "B. Overestimates the overall rate of problem behavior", "C. Does not isolate which reinforcer is necessary", "D. Requires an unusually long observation period"], answer: "C", rationale: "A synthesized condition demonstrates a contingency sufficient to evoke responding but leaves the contribution of each combined component unresolved. Separating necessary from merely sufficient variables is what the standard multielement analysis is designed to do." }
    ]
  },
  {
    day: 127,
    domain: "Behavior Assessment",
    taskCode: "F.4 · Reinforcer Assessment",
    taskDesc: "Design and evaluate preference assessments.",
    concept: {
      title: "Reinforcer Assessment: Relative Versus Absolute Effects",
      body: "A preference assessment ranks stimuli; it does not establish that any of them reinforces behavior. Closing that gap requires a reinforcer assessment, and the arrangement chosen determines which question actually gets answered.\n\nA concurrent-schedule arrangement makes two responses available at once, each producing a different stimulus, and measures allocation between them. This assesses relative reinforcement effects — whether one stimulus is preferred over another. A single-operant arrangement makes one response available producing one stimulus, and compares responding against baseline. This assesses absolute reinforcement effects — whether that stimulus functions as a reinforcer at all. The two questions are genuinely different, and a stimulus can fail the first while passing the second.\n\nThat is not a hypothetical. Stimuli identified as low preference, and reliably outcompeted when a high-preference alternative was concurrently available, have nonetheless maintained responding at high rates when they were the only option. The clinical consequence is direct: a low rank in a competitive preference assessment does not establish that an item is not a reinforcer. It establishes only that it loses to something better.\n\nResponse effort adds a further dimension. Progressive-ratio arrangements escalate the schedule requirement across a session, and the point at which responding breaks down indexes reinforcer strength rather than mere preference. Roane, Lerman and Vorndran (2001) reported that stimuli associated with more responding under increasing requirements were generally more effective in treatment, and drew the practical conclusion that two reinforcers may be similarly effective for low-effort tasks and differentially effective for high-effort ones."
    },
    research: {
      citation: "Roscoe, E. M., Iwata, B. A., & Kahng, S. (1999). Relative versus absolute reinforcement effects: Implications for preference assessments. Journal of Applied Behavior Analysis, 32(4), 479–493.",
      summary: "Roscoe, Iwata and Kahng identified high- and low-preference stimuli for eight participants using single-stimulus and paired-stimulus assessments, then tested those stimuli under both concurrent and single-schedule reinforcement conditions using reversal designs. Under the concurrent arrangement, seven of the eight participants allocated responding consistently to the high-preference stimulus. Under the single schedule, where only the low-preference stimulus was available, six of those seven responded at rates as high as they had for the high-preference stimulus concurrently. The authors concluded that the concurrent procedure is well suited to assessing relative reinforcement effects — preference for one reinforcer over another — but that absolute reinforcement effects associated with a given stimulus may be best examined under single-schedule conditions."
    },
    application: "When an RBT reports that a learner's third-ranked reinforcer \"doesn't work,\" check how it was tested. If the learner also had access to a higher-ranked item, the report describes preference, not reinforcer function. Test it alone against baseline before discarding it, since a usable pool of reinforcers is worth more than a single favorite that will satiate. When work requirements are high, verify that the reinforcer still holds under that effort.",
    questions: [
      { q: "A single-operant reinforcer assessment answers which question about a stimulus?", options: ["A. Is it preferred over the client's highest-ranked item", "B. Does it function as a reinforcer at all", "C. How quickly will the client satiate on it", "D. Which topography of responding does it occasion"], answer: "B", rationale: "A single-operant arrangement compares responding for one stimulus against baseline, which isolates absolute reinforcement effects. Comparison against another stimulus requires a concurrent arrangement and answers a relative question instead." },
      { q: "An item ranked last in a paired-stimulus preference assessment is best described as:", options: ["A. Confirmed to have no reinforcing function", "B. Suitable only for use with high-effort tasks", "C. Outcompeted, but not established as a non-reinforcer", "D. Likely to function as a punisher if delivered contingently"], answer: "C", rationale: "Ranking measures relative allocation among competing options. Roscoe and colleagues found stimuli ranked low under paired-stimulus conditions still maintained responding at high rates alone, so a low rank cannot establish absence of reinforcer function." },
      { q: "Two stimuli produce equal responding on a fixed-ratio 1 schedule but diverge sharply under progressive-ratio requirements. This suggests they:", options: ["A. Are equally effective across all instructional contexts", "B. Should both be removed from the reinforcer pool", "C. Were incorrectly identified by the preference assessment", "D. Differ in strength, which matters for high-effort tasks"], answer: "D", rationale: "Escalating the schedule requirement discriminates reinforcers that appear equivalent at low effort. Roane and colleagues concluded that two reinforcers may be similarly effective for low-effort tasks and differentially effective for high-effort ones." }
    ]
  },
  {
    day: 128,
    domain: "Behavior Assessment",
    taskCode: "F.6 · Automatic Subtypes",
    taskDesc: "Design and evaluate functional analyses.",
    concept: {
      title: "Subtypes of Automatically Reinforced Self-Injurious Behavior",
      body: "One caveat governs everything that follows. This model classifies self-injury already established as automatically reinforced; it is not a route to establishing automatic maintenance. Undifferentiated responding on its own remains ambiguous and still calls for a modified, repeated analysis — typically an extended series of alone sessions, which is how automatic maintenance gets established when analog conditions do not differentiate.\n\nSocial functions have been progressively subdivided for decades while automatic reinforcement remained a single undifferentiated category. Hagopian, Rooker and Zarcone (2015) proposed three subtypes distinguished by functional analysis response pattern together with the presence of self-restraint. Subtype 1 shows clear differentiation between the alone and play conditions with lower responding in play, indicating behavior sensitive to the level of environmental stimulation available. Subtype 2 shows high, sometimes variable responding across all conditions with little sensitivity to environmental manipulation. Subtype 3 is defined by the presence of self-restraint.\n\nThe classification predicts treatment response, which is what makes it clinically consequential rather than merely descriptive. Competing stimulus assessments identified at least one effective stimulus for every Subtype 1 case tested, and for a smaller proportion of Subtype 2 and Subtype 3 cases. Reinforcement alone was effective for most Subtype 1 cases and for none of the Subtype 2 cases evaluated, which required more intensive intervention.\n\nTwo hedges belong with this material. The authors describe the model as preliminary and explicitly decline to alter the recommended practice of proceeding from less to more intensive intervention until prospective research validates it. Their descriptive labels — sensory, strong sensory, and mixed sensory — are offered as speculation about mechanism, not as measured findings."
    },
    research: {
      citation: "Hagopian, L. P., Rooker, G. W., & Zarcone, J. R. (2015). Delineating subtypes of self-injurious behavior maintained by automatic reinforcement. Journal of Applied Behavior Analysis, 48(3), 523–543.",
      summary: "Hagopian, Rooker and Zarcone analyzed thirty-nine consecutive cases of automatically reinforced self-injury against a comparison group of thirteen socially reinforced cases, sorting the automatic cases into three subtypes using functional analysis differentiation and the presence of self-restraint. Roughly forty percent met Subtype 1 criteria, thirty-eight percent Subtype 2, and twenty-one percent Subtype 3. Treatment data separated the groups sharply: reinforcement alone succeeded for eight of twelve Subtype 1 cases and for none of the seven Subtype 2 cases, and effective competing stimuli were identified for a larger proportion of Subtype 1 cases. Level of functional analysis differentiation correlated with response to reinforcement-based treatment. The authors characterize the model as preliminary and warranting further study."
    },
    application: "With medical causes ruled out and automatic maintenance established, look at how differentiated the analysis actually was before you plan treatment. Clear separation between alone and play predicts that reinforcement-based intervention and a competing stimulus assessment are worth running first. High undifferentiated responding predicts they will likely be insufficient on their own — so plan for additional components early, while still working from less restrictive toward more restrictive.",
    questions: [
      { q: "The Hagopian et al. (2015) subtyping model is intended to be applied:", options: ["A. After automatic maintenance has already been established", "B. Before any functional analysis has been conducted", "C. Instead of a functional analysis for dangerous behavior", "D. Only when the behavior is socially reinforced"], answer: "A", rationale: "Every case in the study was already classified as automatically reinforced, and the subtypes sort within that category. The model refines an established function rather than substituting for the analysis that identifies one." },
      { q: "Which functional analysis pattern characterizes Subtype 2 automatically reinforced self-injury?", options: ["A. Elevated responding confined to the demand condition", "B. Low responding in alone with elevation in play", "C. Clear separation between alone and play conditions", "D. High undifferentiated responding across all conditions"], answer: "D", rationale: "Subtype 2 is defined by responding that stays high and sometimes variable regardless of condition, showing little sensitivity to environmental manipulation. Clear alone-versus-play differentiation defines Subtype 1 instead." },
      { q: "Hagopian et al. (2015) reported that reinforcement-based treatment alone was effective for:", options: ["A. All three subtypes at comparable rates", "B. Most Subtype 1 cases but no Subtype 2 cases", "C. Subtype 3 cases only, once restraint was blocked", "D. No cases of automatically reinforced self-injury"], answer: "B", rationale: "Reinforcement alone reduced self-injury for eight of twelve Subtype 1 cases and for none of the seven Subtype 2 cases evaluated. Subtype 2 consistently required more intensive treatment components." }
    ]
  }
]
